name: Main

on:
  - schedule:
      cron: "0 8 * * *"
  - workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        with:
          python-version: 3.14

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-os:ubuntu-24.04-python:3.14-${{ env.pythonLocation }}

      - name: Import SSH Key
        shell: bash
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.DEPLOY_SSH_KEY }}'

      - name: Run
        shell: bash
        run: ./scripts/crawl_upload.sh
